### ISSUE TITLE
port number 9000 is not configurable in application settings

### ISSUE THREAD

**Issue by ranlo** [sentric/hannibal#10]
it's a problem if some other service on the server is already using this port number

**Comment by meniku** [comment]
I don't know how to configure the port via application.conf yet, but I got a workaround for you:

Edit the 'start'-script and change java-command to include the port:

```
java -jar $dir/sbt-launch-0.11.3.jar -DapplyEvolutions.default=true "start 8080"
```

**Comment by ranlo** [comment]
YES! works like magic. Thanks!
