### ISSUE TITLE
Easy way to deploy hannibal

### ISSUE THREAD

**Issue by hercules90** [sentric/hannibal#17]
There should be an easier way to deploy hannibal. An assembly(zip/tar.gz) seems like the best way. Compiling and rebuilding it for every node seems like a very tedious process. Also I wasn't unable to get it building on all my nodes.

**Comment by meniku** [comment]
Maybe we need to fix the README.

In case that I am right with my assumption that by "node" you mean a RegionServer: Hannibal does not need to be deployed on every RegionServer. In fact, it doesn't need to be executed from within your HBase Cluster at all. Hannibal collects metrics for all RegionServers, regardless of where it is installed. Installing it multiple times is unnecessary.

I recommend to run it on a seperate machine if possible.

**Comment by hercules90** [comment]
Is there a way to create an assembly for deployment? I am actually trying to deploy on a util box that connects to our cluster but unfortunately I might not really be able to build the project on that box as specified in the README but rather simply deploy assemblies(tar.gz). Is there any way to do that?

**Comment by meniku** [comment]
playframework has an option to do that, the "stage" task.

Unfortunately this results version-conflict in log4j. I don't have a solution for this yet :(

Things to reproduce:

```
./sbt stage
tar -czf hannibal.tgz target/start target/staged/ conf/
cp hannibal.tgz /tmp
mkdir /tmp/hannibal
cd /tmp/hannibal
tar -xf /tmp/hannibal.tgz
./target/start -DapplyEvolutions.default=true
```

Another problem is that this bypasses the hannibal-start script. so it will ignore the env-var "HANNIBAL_HTTP_PORT" if it has been set. But there may be a workaround for that

For more info look here: https://github.com/playframework/Play20/wiki/Production

**Comment by meniku** [comment]
The script `./create_package` is now compatible with all hbase-versions, it is available in the `next` branch.
It now also contains a correct `./start` script, which behaves just like the normal start script.
