### ISSUE TITLE
Region view doesn't show correct region when start/end keys are non-printable characters

### ISSUE THREAD

**Issue by alexandre-normand** [sentric/hannibal#20]
We have tables that use a 1-byte hash prefix and we noticed that when navigating with hannibal and clicking on the regions that have non-printable characters in the start/end, the region displayed is not the correct one. 

Here's a screenshot showing the problem. The region hover details showed the same region name as we can see in the URL but the region name in the page itself doesn't match the region name of the url.

![bug with unreadable start keys](https://f.cloud.github.com/assets/788439/765254/4b632f70-e826-11e2-845c-a2bf465c3b97.jpg)

I haven't looked at the hannibal code in a while but it seems like there's a need for properly encoding/decoding values that can be bytes (not necessarily strings) and might get lost when formatted as strings.

**Comment by meniku** [comment]
I always feared that case, but never tested it until someone runs into this. I am actually a bit confused that you can reach the region-page at all...

Maybe we could solve this if we just encode the whole Regionname with Base 64.

**Comment by alexandre-normand** [comment]
I think base64 will be a good candidate for the path that is used in the URL/links. It might be worth also looking into taking this opportunity to format those start/end keys for display using hex to make it easier to copy-paste in hbase shell. Something like: http://kernel-panik.blogspot.com/2012/07/reading-binary-key-data-using-hbase.html 

I might look into this when I have some time but anyone is free to give it a try if I don't get to it soon enough.

**Comment by adrien-mogenet** [comment]
I'm working on it!
