### ISSUE TITLE
compaction history chart  duration

### ISSUE THREAD

**Issue by ghost** [sentric/hannibal#28]
hi, I'm using hannibal in a product environments, when I met a problem that in compaction history chart  /compactions, the chart only show compactions of last 24 hour, I want that to be longer.
Is there any configurations that could help this problem?

ps: I already set  "metrics.clean-threshold" to a week in conf/application.conf, 
and "metrics.clean-interval" is default 43200.

**Comment by meniku** [comment]
I'm just writing the result of our E-Mail conversation. If someone wants to work on that...

There is no such configuration right now, however this can be easily added (but it can reduce performance badly). It can be enabled by adding a `range`-pamameter to the `Matrics.byNames` call

For example, a hardcoded 1 week duration can be achieved by replacing the following Lines for the  `byNames` method in `app/assets/javascripts/models/Metric.coffe`:

```
  @byNames: (names) ->
    metrics = new Metrics([])
    metrics.url = Routes.Api.metrics
      metric: names
    metrics
```

to this:

```
  @byNames: (names) ->
    metrics = new Metrics([])
    metrics.url = Routes.Api.metrics
      metric: names
      range: new Date().getTime() - 1000 * 60 * 60 * 24 * 7 # e one Week
    metrics
```

**Comment by meniku** [comment]
@249550148 We just released a new alpha-version of Hannibal which introduces the new configuration parameter `metrics.default-range` for this.

You can grab it from here: https://github.com/sentric/hannibal/releases/tag/v.0.10.1-alpha

Please report any issues
