### ISSUE TITLE
HBase 0.96 support

### ISSUE THREAD

**Issue by junegunn** [sentric/hannibal#30]
Hi, first of all, thanks for the project.
We've been using it for months and it has been really helpful. However, we recently deployed a new CDH5 cluster which runs HBase 0.96.1.1 and realized hannibal doesn't work there. Any plan to support HBase 0.96 or above?

**Comment by meniku** [comment]
Yes we are currently working on HBase 0.96 support. I hope to get it working this week, but cannot promise it.

**Comment by junegunn** [comment]
Thanks! :+1:

**Comment by meniku** [comment]
@junegunn I added an alpha release for working HBase 0.96 support, you can grab it here: https://github.com/sentric/hannibal/releases/tag/v.0.10.1-alpha

Please report any problems.

**Comment by junegunn** [comment]
Sorry, I haven't found time to test it, and we have moved on to 0.98 as with the release of CDH5.1. You can close this issue if you want.

**Comment by meniku** [comment]
OK. 

I added a release for hbase 0.98 as well.

https://github.com/sentric/hannibal/releases/tag/v.0.10.1
