### ISSUE TITLE
Configurable timezone in Rickshaw chart

### ISSUE THREAD

**Issue by sunzhu** [sentric/hannibal#35]
From Nils:
We use Rickshaw for client side rendering of the graphs. Unfortunately, this seams to be not yet implemented in Rickshaw: https://github.com/shutterstock/rickshaw/issues/140 . However there are some workarounds posted there.

**Comment by meniku** [comment]
Hannibal now uses timezone is from the browser, checkout the latest alpha release from https://github.com/sentric/hannibal/releases
