### ISSUE TITLE
Usability of Cluster screen

### ISSUE THREAD

**Issue by ranlo** [sentric/hannibal#6]
A list of usability issues:
- List of tables is not sorted, making it very difficult to find a certain table
- if table names are longer than allocated space the panel will grow to show the longest name, overrunning the graphs
- deselecting tables needs to be done one by one. so if I am only interested in one table, i need to go over all of them, deselect, and then select only the one I'm interested in
- after selecting only the tables i am interested in, if I 'drill down' into a table and return to the cluster screen, it is reset to 'all tables'

**Comment by meniku** [comment]
Thank you very much for the suggestions, I hope that I find time soon to begin working on that.
