### ISSUE TITLE
Region Distribution graph not showing colors.

### ISSUE THREAD

**Issue by morganda** [sentric/hannibal#8]
I checked in the latest version of Safari, Chrome, and Firefox but it only shows the graphs for my middle region server. When I hover over the region server sections I can see that each region server does in fact have around 333 regions assigned. As you can see from the screenshot, each table is checked, but it is only showing the .META. table.

![Screen Shot 2012-12-14 at 5 42 51 PM](https://f.cloud.github.com/assets/1540803/14568/81e045ec-4650-11e2-8d8c-ce8877d7d225.png)

**Comment by meniku** [comment]
Would it be possible for you to send me the the output of:

http://[hannibal-server]:9000/regions/.json

to me?

**Comment by morganda** [comment]
Well that's what I get for staying late at work on a Friday night. I looked at the y axis and realized the graph is based on actual storage size and not the number of regions. Closing this.
